languageCode = "pt-br"
title = "Lab TravisCI HostGator"
baseurl = "http://lab-travisci.devopszone.net"
theme = "hugo-future-imperfect"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Some description"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Cool title"

[params.intro]
    header    = "This is a header"
    paragraph = "This is a paragraph"
    about     = "Lorem ipsum dolor sit amet..."

[params.postAmount]
    sidebar = 2

[[menu.main]]
    name = "Blog"
    url = "/blog"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
